permissions:
  contents: write
  packages: write

name: React CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  #1️ Test on Dev Branch
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests (Dev)
        run: npm test -- --watchAll=false --ci --json --outputFile=test-results.json
        env:
          CI: true

      - name: Upload JSON test results (Dev)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-dev
          path: test-results.json

  #2️ Merge Dev -> Main
  merge-to-main:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout main
          git merge dev --no-edit
          git push origin main

  #3️ Test on Main after merge
  test-main:
    needs: merge-to-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install

      - name: Run tests (Main)
        run: npm test -- --ci --watchAll=false --json --outputFile=test-results-main.json
        env:
          CI: true

      - name: Upload JSON test results (Main)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-main
          path: test-results-main.json

  #4 Sync Main -> Dev (only after test-main passes)
  sync-main-to-dev:
    needs: [test-main]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Merge main back to dev
        run: |
          git checkout dev
          git merge main --no-ff -m "Sync main into dev [skip ci]"
          git push origin dev

  build:
    needs: sync-main-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
