name: React CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --ci --reporters=default --reporters=jest-junit
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: junit.xml

  merge-to-main:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge dev -> main
        run: |
          git checkout main
          git merge dev --no-edit
          git push origin main

      - name: Sync main -> dev
        run: |
          git checkout dev
          git merge main --no-edit
          git push origin dev

  build:
    needs: merge-to-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
